dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

virtualenv:
  system_site_packages: true

install:
  - pip install pipenv
  - pipenv install --dev 

script:
  - pipenv run pytest
